"""empty message

Revision ID: 1555ace85c8b
Revises: 
Create Date: 2024-11-01 07:50:49.886710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1555ace85c8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('pfp', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), server_default='prefer_not_to_say', nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client_match',
    sa.Column('my_email', sa.String(), nullable=False),
    sa.Column('liked_email', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['liked_email'], ['client.email'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['my_email'], ['client.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('my_email', 'liked_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_match')
    op.drop_table('client')
    # ### end Alembic commands ###
