"""empty message

Revision ID: 137bf4460735
Revises: 1555ace85c8b
Create Date: 2024-11-01 08:25:27.966783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137bf4460735'
down_revision: Union[str, None] = '1555ace85c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_match', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('client_match', sa.Column('liked_client_id', sa.Integer(), nullable=False))
    op.drop_constraint('client_match_my_email_fkey', 'client_match', type_='foreignkey')
    op.drop_constraint('client_match_liked_email_fkey', 'client_match', type_='foreignkey')
    op.create_foreign_key(None, 'client_match', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_match', 'client', ['liked_client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('client_match', 'liked_email')
    op.drop_column('client_match', 'my_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_match', sa.Column('my_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client_match', sa.Column('liked_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_match', type_='foreignkey')
    op.drop_constraint(None, 'client_match', type_='foreignkey')
    op.create_foreign_key('client_match_liked_email_fkey', 'client_match', 'client', ['liked_email'], ['email'], ondelete='CASCADE')
    op.create_foreign_key('client_match_my_email_fkey', 'client_match', 'client', ['my_email'], ['email'], ondelete='CASCADE')
    op.drop_column('client_match', 'liked_client_id')
    op.drop_column('client_match', 'client_id')
    # ### end Alembic commands ###
