"""empty message

Revision ID: 32c3108911d2
Revises: 07fe1ac26cc8
Create Date: 2024-11-01 16:00:35.977867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c3108911d2'
down_revision: Union[str, None] = '07fe1ac26cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('latitude', sa.Double(), nullable=False))
    op.add_column('client', sa.Column('longitude', sa.Double(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'longitude')
    op.drop_column('client', 'latitude')
    # ### end Alembic commands ###
